// generated by cdktf get
Object.defineProperty(exports, 'profile', { get: function () { return require('./profile'); } });
Object.defineProperty(exports, 'user', { get: function () { return require('./user'); } });
Object.defineProperty(exports, 'userRole', { get: function () { return require('./user-role'); } });
Object.defineProperty(exports, 'dataSalesforceProfile', { get: function () { return require('./data-salesforce-profile'); } });
Object.defineProperty(exports, 'dataSalesforceUserLicense', { get: function () { return require('./data-salesforce-user-license'); } });
Object.defineProperty(exports, 'provider', { get: function () { return require('./provider'); } });

